apiVersion: v2

name: cert-manager-istio-csr
type: application
description: istio-csr enables the use of cert-manager for issuing certificates in Istio service meshes

home: https://cert-manager.io/docs/usage/istio-csr/
maintainers:
- name: cert-manager-maintainers
  email: cert-manager-dev@googlegroups.com
  url: https://cert-manager.io
sources:
- https://github.com/cert-manager/istio-csr

appVersion: v0.0.0
version: v0.0.0
